name: Upload file
description: Upload a file to repo's storage
inputs:
  azure-blob-storage-connection-string:
    description: The connection string of Azure Blob Storage.
    required: true
  azure-blob-storage-container:
    description: The container of Azure Blob Storage.
    required: true
  target-file:
    description: The target file path (aka. blob file name) in Azure Blob Storage.
    required: true
  file:
    description: The local file to upload.
    required: false
    default: ''
  file-content:
    description: The file content to upload.
    required: false
    default: ''
  cache-control:
    description: The value of the Cache-Control reponse header when accessing the file.
    required: false
    default: no-cache
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        FILE_IS_TEMP="false"
        if [[ "$FILE" == "" ]]; then
            FILE_IS_TEMP="true"
            FILE="$(mktemp -t "file-XXXXXXXX")"
            echo "$FILE_CONTENT" > "$FILE"
        fi
        
        az storage blob upload --connection-string "$AZURE_BLOB_STORAGE_CONNECTION_STRING" --container-name "$AZURE_BLOB_STORAGE_CONTAINER" --file "$FILE" --name "$TARGET_FILE" --content-cache "$CACHE_CONTROL"

        if [[ "$FILE_IS_TEMP" == "true" ]]; then
            rm "$FILE"
        fi
      env:
        AZURE_BLOB_STORAGE_CONNECTION_STRING: ${{ inputs.azure-blob-storage-connection-string }}
        AZURE_BLOB_STORAGE_CONTAINER: ${{ inputs.azure-blob-storage-container }}
        TARGET_FILE: ${{ inputs.target-file }}
        FILE: ${{ inputs.file }}
        FILE_CONTENT: ${{ inputs.file-content }}
        CACHE_CONTROL: ${{ inputs.cache-control }}
