definitions:
  os:
    archlinux:
      name: Arch Linux
      docker-image: menci/aur-builder:archlinux
    manjaro:
      name: Manjaro
      docker-image: menci/aur-builder:manjaro
  arch:
    - x86_64
    - aarch64
baseOptions:
  x86_64: true
  aarch64: false
  archlinux: true
  manjaro: true
packages:
  azure-cli: { aarch64: true }
  azure-storage-fuse:
  besttrace:
  checkra1n-cli:
  curl-http3: { aarch64: true }
  fcitx-sogoupinyin: { ref: aur-74a52e0854ebeb828abbaf529abb00f23066cc28 }
  lemon-lime: { aarch64: true }
  ossutil-bin:
  overture: { aarch64: true }
  powershell-bin:
  yay-bin: { manjaro: false, aarch64: true }
