definitions:
  os:
    archlinux:
      name: Arch Linux
      docker-image: menci/aur-builder:archlinux
    manjaro:
      name: Manjaro
      docker-image: menci/aur-builder:manjaro
  arch:
    - x86_64
    - aarch64
baseOptions:
  x86_64: true
  aarch64: false
  archlinux: true
  manjaro: true
packages:
  azure-cli: { aarch64: true }
  azure-storage-fuse: { aarch64: true }
  besttrace:
  binfmt-qemu-static-all-arch: { aarch64: true }
  box64: { aarch64: true, x86_64: false }
  cf-tool: { aarch64: true }
  checkra1n-cli: { aarch64: true }
  cpeditor: { aarch64: true }
  curl-http3:
  dotnet-core-bin: { aarch64: true, x86_64: false }
  fcitx-sogoupinyin: { ref: aur-74a52e0854ebeb828abbaf529abb00f23066cc28 }
  frp: { aarch64: true }
  lemon-lime: { aarch64: true }
  ossutil-bin:
  overture: { aarch64: true }
  pacman-auto-update: { aarch64: true }
  pacman-static: { aarch64: true }
  pmdk: { aarch64: true }
  powershell: { aarch64: true }
  qemu-user-static-bin: { aarch64: true }
  uwufetch: { aarch64: true }
  xray: { aarch64: true, x86_64: false }
