name: Parse Config
description: Parse config.yaml for job matrix
inputs:
  config-file:
    description: The config.yaml file path.
    required: true
outputs:
  config:
    description: The parsed config JSON string.
    value: ${{ steps.parse.outputs.config }}
runs:
  using: composite
  steps:
    - id: parse
      shell: bash
      run: |
        yarn --cwd "$ACTION_PATH" --frozen-lockfile
        CONFIG_OUTPUT="$(node "$ACTION_PATH"/index.js "$CONFIG_FILE")"
        echo "config=$CONFIG_OUTPUT" >> $GITHUB_OUTPUT
      env:
        ACTION_PATH: ${{ github.action_path }}
        CONFIG_FILE: ${{ inputs.config-file }}
