name: Build Builder Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        # TODO: parse from config
        include:
          - name: archlinux
            from: menci/archlinuxarm:base-devel
            package-type: pacman
          - name: manjaro
            from: manjarolinux/base:latest
            package-type: pacman
          - name: ubuntu-22.04
            from: ubuntu:22.04
            package-type: deb
          - name: ubuntu-20.04
            from: ubuntu:20.04
            package-type: deb
          - name: debian-11
            from: debian:11
            package-type: deb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: builder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: menci/package-builder:${{ matrix.name }}
          build-args: |
            FROM=${{ matrix.from }}
            PACKAGE_TYPE=${{ matrix.package-type }}
